### PR TITLE
Fixed compatibility issues under Xcode 15.0

### PR DESCRIPTION
**Pull request by Magic-Xin**
Fixed compatibility issues under Xcode 15.0 which seems caused by C++17 standard.

### CODE REVIEW

**Comment by FunJim** [comment]
Could someone review this PR? Currently pyopenjtalk build is failed on macOS Sonoma (see https://github.com/r9y9/pyopenjtalk/issues/75)

**Comment by r9y9** [comment]
I am sorry that I was unable to check this PR. I will try to make some time in this weekend to look into this issue

**Comment by w568w** [comment]
Bump. @r9y9, do you have time to review this now?

This is a simple PR that removes the deprecated and now invalid `register` keywords from `src/mecab`.

It seems the original author intended to improve performance with `register`, but compilers have ignored this keyword for a long time. Removing it won't affect the final binary, thus **this PR is purely a clean-up, eliminating an outdated and ineffective part of the code**!

**Rationale**: Clang 18.1.8 has already removed support for `register` and treats it as an error. GCC 14.1.1 is slightly more tolerant but will also stop supporting it very soon.

**Comment by r9y9** [comment]
I apologize for the super delay. I checked this PR works OK with clang 18

```
clang version 18.1.8 (https://github.com/llvm/llvm-project.git 3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff)
Target: arm64-apple-darwin22.6.0
Thread model: posix
```

**Comment by r9y9** [comment]
Thank you very much, @Magic-Xin and @w568w

**Pull request merged**
